/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import java.util.Map;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        Map<String, Object> result = classUnderTest.getGreeting("Test");
        assertEquals("Hello Test!", result.get("message"));
    }
}
